name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist --optimize-autoloader"

jobs:
  confirm-fixtures:
    name: Confirm test fixtures generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate fixtures
        run: |
          touch new.txt
          rm SECURITY.md
          ls
          git diff --cached --exit-code
